pipeline{
    agent any 
    triggers{
        githubPush()
    }
    stages{
        stage('Build'){ //build using maven
            steps{
                script{
                    sh 'pip install -r app1/requirements.txt'
                    sh 'pip install -r app2/requirements.txt'
                }
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    // Build Docker image for app1
                    sh 'docker build -t app1-image ./docker/app1'

                    // Build Docker image for app2
                    sh 'docker build -t app2-image ./docker/app2'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker run -d --name app1 -p 8081:5000 app1-image'
                sh 'docker run -d --name app2 -p 8082:5000 app2-image'
            }
        }
    }
    post {
        always {
            // Clean up unused Docker images and containers (optional)
            sh 'docker image prune -f'
        }
    }
}